name: Python Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run Python script
      run: |
        echo "print('Hello World')" > hello.py
        python Two-layer_FER_vs_PE_vs_r1_NA.py
